[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[mypy_django_plugin]
ignore_missing_model_attributes = true

[[tool.mypy.overrides]]
module = "dj_rest_auth.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "allauth.*"
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "config.settings"
