# Generated by Django 3.2.8 on 2021-10-23 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vampire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('prompt_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='games.promptgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vampires', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_checked', models.BooleanField(default=False)),
                ('vampire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='games.vampire')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_diary', models.BooleanField(default=False)),
                ('is_lost', models.BooleanField(default=False)),
                ('vampire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='games.vampire')),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('description3', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='games.promptgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_forgotten', models.BooleanField(default=False)),
                ('diary', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='games.resource')),
                ('vampire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='games.vampire')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('vampire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='games.vampire')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='games.memory')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='games.prompt')),
                ('vampire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='games.vampire')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_immortal', models.BooleanField(default=False)),
                ('is_dead', models.BooleanField(default=False)),
                ('vampire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='games.vampire')),
            ],
        ),
        migrations.AddConstraint(
            model_name='prompt',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('group', 'order'), name='unique_group_order'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('vampire', 'order'), name='unique_vampire_order'),
        ),
    ]
